runtime: python37
default_expiration: '2s'

handlers:
- url: /
  static_files: serverless-bowties-1/index.html
  upload: serverless-bowties-1/index.html
  expiration: '2s'

- url: /
  static_dir: serverless-bowties-1 
  expiration: '2s'